CHANGELOG.md
src/modules/subjoin/module_subjoin.cpp
test/pepsirf_test.cpp
test/test_score_matrix.tsv

Name list no longer required. When not provided, a warning is given, and all columns from matrix file will be output.

Feature subjoin without namelist

---

CHANGELOG.md
src/modules/info/module_info.cpp

To prevent rounding of larger sums, the notation was changed to fixed-point notation. Values now appear as a float value with the left side of decimal point allowing an non rounded integer and the right side of the decimal point fixed to two digits.

Feature info increase significant digits

---

CHANGELOG.md
src/modules/p_enrich/options_parser_p_enrich.cpp

Changed output_suffix flag to -a (referring to affix) instead of -s to distinguish from sample -s.

Changed output_suffix flag

---

src/modules/deconv/module_deconv.cpp

Deconv now throws error when the --linked file format does not contain :score.

Standardize deconv file format

---

include/modules/subjoin/options_subjoin.h
src/modules/subjoin/module_subjoin.cpp
src/modules/subjoin/options_parser_subjoin.cpp
src/modules/subjoin/options_subjoin.cpp

Changes:
- Input argument for what was -f is has now become two separate flags, -m and -i. -m takes a filename containing filename pairs and -i takes a single filename pair, where the pairs in both cases are a matrix and name list. Option to exclude a name list and opt for all matrix samples to be used is still available for both flags.
- -f, filter_scores flag is removed.
- The program previously read the title "sequence names" in matrix file when no sample name list was given and warned of its exclusion from the computation. This has been updated to not give a warning for this.

Bug subjoin file input distinction

---

CHANGELOG.md
src/modules/p_enrich/module_p_enrich.cpp

Segfaults and other output issues were related to incorrect threshold verification. The raw score threshold and matrix thresholds were stored incorrectly causing incorrect checks.

Bug penrich raw data segfault

---

CHANGELOG.md
include/modules/demux/samplelist_parser.h
src/modules/demux/samplelist_parser.cpp

Added samplelist checking function to verify matching index names between the samplelist and fasta index file.
If the --index option file does not contain names that are present in the --samplelist option file, then a warning is output to the terminal stating missing names are included in the samplelist file and lists the missing names. This issue closes with v1.3.6.
Closes #96

demux-ISS96, handling missing names in index file

---

src/modules/zscore/options_parser_zscore.cpp

The --bins option must take a tsv only containing peptide names. A cryptic error occurred after a score matrix was instead provided. This prompted adding a feature to verify the correct file was provided. To check the file the second line of the file is read. If it contains a number(double, NaN, or infinity), then an error message is thrown and stating the incorrect file has been given for the --bins option. This was chosen as the way to check, because the second line of a score matrix will always contain numerical values or complex noncalculable values (inf/NaN). The only concern is if a name in an appropriate bins file contains 'nan' or 'inf', it can still be read as a numerical value and cause an error. A note on this is provided in the error message to inform a user in the case they …

zscore-ISS97, zscore error message occurs when providing incorrect file to --bins

---

include/modules/core/matrix.h
include/modules/subjoin/module_subjoin.h
src/modules/subjoin/module_subjoin.cpp

In subjoin, a namelist can be provided alongside a score matrix. This namelist acts as a filter, where the file can contain up to two columns of names. The first column is a list of the names that can be found in the matrix and are desired to be included in the process of the run. The second column can contain name updates for the first column. The issue in subjoin was with these name updates. If a name update was a name already used in the matrix, even if it was being updated itself, then the names in the output could be switched around incorrectly. This had to do with the way the data was stored - the names are not stored in a sequential structure and are accessed stochastically. Subjoin should now properly update names when necessary and in the case of an attempted duplicate name in …

subjoin-ISS99, subjoin output column/row names mixed/disordered

---

src/modules/demux/module_demux.cpp
src/modules/zscore/options_parser_zscore.cpp

The output for the diagnostics in the command-line interface should consist of counts for the number of instances a distinct index1 barcode/index name found a match in the reads, the number of counts where a given index1 match occurred followed by a paired index2 match (pair match), and when a pair match in ref-depend mode occurs, if a variable region match occurs the count should increment. The diagnostic file should contain matches specific to the samplename it occurred. When an index/barcode name has a match it should be counted for every sample that includes that index. A pair match should only be valid if the indexes are a pair for a given sample, opposed to being names that are present in the samplesheet, but not paired up. And the count for variable region matches, if applicable, …

demux-ISS100, diagnostics incorrectly calculated for both optional output file and terminal output

---

extensions/enrichedScatterplots.py

Adding the command-line options for the size of points (**--ptsSize**) to be plotted, with a default of 10 and the transparency of points (**--ptsTrans**) to be plotted, with default of 0.5.

extensions-enrichedScatterplots Adding Command-Line Options (Size and Transparency)

---

extensions/enrichedScatterplots.py

Adding the command-line option (-f, --enrFile) for a tab-delimited file to be provided containing the file paths of the enriched files and the sample names. Command-line option (-e, --enrDir) for a directory containing the enriched files is still maintained, as well as all original functionality.
The user is able to provide both a directory and a file, but the file will be the default, and the user must provide at least one. Warnings have been added for both scenarios.

option for enriched file containing path and names

---

extensions/enrichedScatterplots.py

Updating "--plotLog" command-line option to now be accompanied by a floating-point argument that will be added to the points prior to log normalization. In addition, both axes labels will have "log10(value+plotLogargument)" added to the end of them when "--plotLog" is selected.
Adding "-i"/"--negative_id" as a command-line option to be used in place of the command-line option "-c"/"--negativeControl". It will allow the user to provide a string that is unique to the start of the negative control samples (code will make use of string.startswith() to accomplish this). If no samples were found matching the negative ID, a warning will be issued.

updating plogLog and adding negative_id - issue119/20

---

include/modules/normalize/module_normalize.h
src/modules/normalize/module_normalize.cpp

The norm module incorrectly assumed the order of peptide names in the matrices. This has been updated to no longer order under the assumption the peptides in the original matrix and the control matrix are the same. This issue only relates to the approaches that utilize a control.
Closes #125

Updated the norm module handling differently ordered matrices

---

CHANGELOG.md
include/modules/enrich/module_enrich.h
include/modules/enrich/options_enrich.h
src/modules/enrich/module_enrich.cpp
src/modules/enrich/options_enrich.cpp
src/modules/enrich/options_parser_enrich.cpp

This issue focused on an enhancement for the enrich module. If a replicate fails to meet a raw score or matrix threshold specified, it will result in the replicate set containing that replicate failing to generate any peptides. This additional option ("--enrichment_failure_reason, -f") being added will be helpful in giving more context to the user why the failure occurred. The plan is to expand this a little further in the future. Currently, a file with header "Replicates   Reason" is created. The replicates column contains a comma-delimited list of replicates and the reason column contains the respective reasoning for why the replicate set didn't generate an enriched peptides file.

Enrich iss103 - Failure to generate enriched peptides reasoning output

---

extensions/autoPepSIRF.py

Add a new command-line option "--enrichedScatters" to allow automatic generation of scatterplots that compare col-sum normalized read counts between a sample and negative controls.
The flag is accompanied by an argument of how to call enrichedScatterplots.py, so it can be called to generate the plots.
If p_enrich module is not run, a warning will be printed and the flag will be set to false. Otherwise, a enrichedScatterplots, directory, containing the plots, will be placed in the enriched peptides directory.

add --enrichedScatters option

---

src/modules/link/metadata_map.cpp
src/modules/link/module_link.cpp

Updating the verification of ids to return an empty string instead of a zero integer. This way an error can be thrown if a sequence is not found as a match in the metadata map. This was developed during a meeting with Isaiah. Instead of comparing the sizes of protein sequences and the sequence ids in the metadata file, throwing an error when an id is not found in metadata may be a more suitable update to this. The former way of verifying the two datasets assumes the metadata file and the protein sequences file will contain the same amount of data. This change will not base off size and make that assumption.

Updating the link module to handle unfound sequences in metadata

---

extensions/autoPepSIRF.py

Add Argument "--v13" to keep compatibility with lesser versions than version 1.4. If the argument is provided, the enrichment module is set to p_enrich and the output file is set to penrich.out. Otherwise, version 1.4 is assumed and the enrichment module is set to enrich and the output file is set to enrich.out.

Make autoPepSIRF compatible with version 1.4 and 1.3

---

include/modules/demux/module_demux.h
src/modules/demux/module_demux.cpp

Adding ref-independent mode feature. Duplicate probe sequence names will not be included in the final output, but will still be used in the demultiplexing process. Closes #138

Demux iss138

---

CHANGELOG.md
src/modules/demux/module_demux.cpp
src/modules/demux/samplelist_parser.cpp

Update to samplelist parser to catch and output duplicate sample names or index names. Also fixed a bug in diagnostic output that got overwritten causing a bug. Diagnostic info should only be output if the filename is provided.
There was also an unused variable that could be removed. Closes #35

Add duplicate checking in demux - samplename and index name set duplicates

---

extensions/autoPepSIRF.py

Updated warning from "Not going to be able to do much without a score matrix of some type." to a more descriptive warning of "Not going to be able to do much without one of the following arguments: --raw, --colsum, --diff, --diffratio, --zscore. Refer to usage documentation.".

Make no score matrix warning more descriptive

---

test/pepsirf_test.cpp

This most recent commit includes removal of tests made unnecessary after removing unused/unnecessary methods from setops.h and util.h. In addition, replacing spaces with explicit '\t' characters for tabs when trying to get lines from a line set when testing info module's creation of columns sums file should allow pepsirf_test to be built across platforms. The verbosity is also useful.

Pepsirf test iss152
