LadnerLab/PepSIRF

- src/modules/bin/options_parser_bin.cpp
- src/modules/deconv/options_parser_deconv.cpp
- src/modules/demux/options_parser_demux.cpp
- src/modules/info/options_parser_info.cpp
- src/modules/link/options_parser_link.cpp
- src/modules/normalize/options_parser_normalize.cpp
- src/modules/p_enrich/options_parser_p_enrich.cpp
- src/modules/s_enrich/options_parser_s_enrich.cpp
- src/modules/subjoin/options_parser_subjoin.cpp
- src/modules/zscore/options_parser_zscore.cpp
Updated the help info provided by -h option for each module of PepSIRF.
> Feature update help info

- CHANGELOG.md
- CMakeLists.txt
> Disable ZLib on Mac systems.

- src/modules/link/options_parser_link.cpp
Fixes duplicate --meta flag option.
> Removed duplicate flag for meta.

- CHANGELOG.md
- src/modules/s_enrich/module_s_enrich.cpp
> Fixed s_enrich sample name shuffling bug

- src/modules/subjoin/module_subjoin.cpp
- src/modules/subjoin/options_parser_subjoin.cpp
Fixed implementatilon of no samplelist requirement in subjoin module.
> Subjoin samplelist bug

- CHANGELOG.md
- include/modules/core/peptide_scoring.h
- include/modules/zscore/module_zscore.h
- include/modules/zscore/options_zscore.h
- src/modules/core/peptide_scoring.cpp
- src/modules/zscore/module_zscore.cpp
- src/modules/zscore/options_parser_zscore.cpp
- src/modules/zscore/options_zscore.cpp
- test/pepsirf_test.cpp
> Feature zscore hdi support

- include/modules/subjoin/options_subjoin.h
- src/modules/subjoin/module_subjoin.cpp
- src/modules/subjoin/options_parser_subjoin.cpp
- src/modules/subjoin/options_subjoin.cpp
Reverts LadnerLab/PepSIRF#86
Will be reverting to include the linked issue.
> Revert "Bug subjoin file input distinction"

- include/modules/subjoin/options_subjoin.h
- src/modules/subjoin/module_subjoin.cpp
- src/modules/subjoin/options_parser_subjoin.cpp
- src/modules/subjoin/options_subjoin.cpp
Reverts LadnerLab/PepSIRF#87
Also must close #83
> Revert "Revert "Bug subjoin file input distinction""

- extensions/pepCorrelations.py
adding pepCorrelations that takes in a data file, computes correlations between the peptides, then outputs the information into a tab-delimited file.
> add pepCorrelations

- src/modules/enrich/module_enrich.cpp
- src/modules/enrich/options_parser_enrich.cpp
Updating the messages output to the user. The help messages and the reason message for the enrichment failure flag. Closes #103
> Updating the enrich module help messages and reasoning messages for tracing.

- extensions/autoPepSIRF.py
integrate new inout function to fix issues with generations of scatterplots.
> Integrating new inout.py function

- extensions/enrichedScatterplots.py
Create a --zenrfiles option that will take in a .tsv file containing the z score threshold and the associated enriched directories in ascending order.
Scatterplots will be generated, enriched peptides will be colored based on their z score threshold and a legend will be added to the plot containing the z score thresholds.
> Create option to generate scatters will multiple z score thresholds

- src/modules/zscore/module_zscore.cpp
Ensures that peptide and bins file match in the zscore module.
> Add bins/peptide check

- src/modules/demux/module_demux.cpp
Additional changes for multithreading have been added by Isaiah. The results of testing for this branch are as expected. The output and diagnostic files as well as the terminal output all generate correct match counts. Further testing can commence in the develop branch.
> Demux iss163

- .github/workflows/cppCI.yml
- src/modules/enrich/module_enrich.cpp
- test/pepsirf_test.cpp
Closing #154. Issue created to prevent pipeline issue in PepSIRF q2 plugin where no enrichment.
> Modified output to create output files even if no enriched peptides.

- include/modules/demux/module_demux.h
- src/modules/demux/module_demux.cpp
> Demux iss168

- include/modules/link/module_link.h
- src/modules/link/metadata_map.cpp
- src/modules/link/module_link.cpp
Fixes discrepancy where user was warned about excluded protein sequences regardless of whether or not those sequences were specified in the protein file.
> Link iss210

- include/modules/demux/module_demux.h
- include/modules/demux/options_demux.h
- src/modules/demux/module_demux.cpp
- src/modules/demux/options_demux.cpp
- src/modules/demux/options_parser_demux.cpp
Created output for:
1) Number of samples 
2) Number of replicates (new option for output file with more specific information_
3) Number of samples starting with “Sblk_”
> Sample list information

- include/modules/demux/module_demux.h
- include/modules/demux/options_demux.h
- src/modules/demux/module_demux.cpp
- src/modules/demux/options_demux.cpp
- src/modules/demux/options_parser_demux.cpp
Reverts LadnerLab/PepSIRF#228, testing if storage will run out again
> Revert "Sample list information"

- include/modules/demux/module_demux.h
- include/modules/demux/options_demux.h
- src/modules/demux/module_demux.cpp
- src/modules/demux/options_demux.cpp
- src/modules/demux/options_parser_demux.cpp
> Revert "Revert "Sample list information""

- extensions/linkageMap2GMT.py
Converts linkage map to a gmt (sample command included in script)
> Create linkageMap2GMT.py script
